spring:
 datasource:
   url: jdbc:postgresql://my-postgres-db:5432/todoapp
   username: postgres
   password: password
   driver-class-name: org.postgresql.Driver
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       format_sql: true
server:
 port: 8080